### PR TITLE
Views

### PR DESCRIPTION
**Pull request by Tobby8629**
## In this milestone

- implemented the design as given in the wireframes,
- populated the database with data that is being displayed in the view, and
- checked and verified that pages were rendering accordingly.

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Tobby, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

As an error is thrown in an attempt to setup this project due to unidentified/mismatch field. Kindly ensure to resolve the same.
 
**Setup error due to unidentified field:**
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Tobby8629** [comment]
@rloterh Thank you for the review, I tried to check on the error so I can fix it but I did not get any error of such can you please put me through how you encountered the error

**Review by Qoosim — APPROVED** [review]
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @Tobby8629, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 



## Optional suggestions

- [OPTIONAL] There was a debate on you creating comment inside your migration files before creating post which is why that error is being thrown. I would suggest to look into this while creating your future rails apps. We were able to resolve this after running rails db:setup. Your App works fine. All the best in your future projects. :handshake: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rloterh** [comment]
> @rloterh Thank you for the review, I tried to check on the error so I can fix it but I did not get any error of such can you please put me through how you encountered the error

Hi @Tobby8629 

This error occurred during a process of running migration.
I've checked thoroughly and same error still surface.

The only configuration changes I made during setup was to change the ruby version used from 3.2.1 to 3.2.2, perhaps might be cause of the error on my side.

I'm however glad that your project has been successfully approved! 👏 👏 

Cheers! 😃

**Comment by Tobby8629** [comment]
Thank you very much for looking into it, I will take note next time

**Pull request merged**
