### PR TITLE
Controllers spec

### PR DESCRIPTION
**Pull request by Tobby8629**
##In this milestone, I completed the following requirements;

- Add RSpec as a gem to your project.

- Create a Request spec file for all your controllers.

- Make sure that for each action you check:

  - If response status was correct.

  - If a correct template was rendered.

  - If the response body includes correct placeholder text.

### CODE REVIEW

**Review by victorokoroji — CHANGES_REQUESTED** [review]
Hi @Tobby8629 , 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- All tests are passing ✅ 
- The PR title and description are professional and descriptive ✅ 

## Required Changes ♻️

- [ ] Good job so far 👍🏽 . The issue is that I keep getting this error below while trying to run the migrations files. This error occurred because the migrations run sequentially according to the file. In your case, you have comments migrations before the posts migration file and while running the comments migrations, the post table does not exist yet hence causing this error.
image. 
A fix will be to re-order the migration files so that the post migrations come before the comments migration files so that your app can be properly tested.

_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Tobby8629** [comment]
@vickymarz Thank you for the review, I tried to check on the error so I can fix it but I did not get any error of such can you please put me through how you encountered the error
rails-solution

**Comment by victorokoroji** [comment]
@Tobby8629, I can see that you have gotten similar suggestions on this same issue before. I believe you should have looked into it and fixed it.

I encountered the error when I ran rails `db:migrate`

i suggest you drop your database by running `rails db:drop db:create db:migrate` to see if the error will appear on your end

**Review by victorokoroji — CHANGES_REQUESTED** [review]
Hi @Tobby8629, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️

- [ ] Even after running `rails db:setup `I still got the same error I mentioned earlier. Kindly fix this by deleting your migration files and create the migrations (table) again in sequence

- users
- posts
- comments
- likes

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Ismailco — COMMENTED** [review]
Hi @Tobby8629, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

I do not want to request changes because this is your last review, kindly make sure to fix the migration error and request a new review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by franclobo — COMMENTED** [review]
Hi @Tobby8629, 

terminator

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't complete the previously required changes 👇🏽 
I recommend using [ChatGPT](https://chat.openai.com/) for this kind of issue.

image

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED ✔🍾🎉🎉**
Hello @Tobby8629 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Correct git-flow.
- Descriptive PR.
- Good commit messages.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
